name: k8s_deploy.yml

on:
  workflow_dispatch:
  push:
    paths-ignore: 
      - '**/workflows/hacks/*.yml'
    paths: 
      - 'k8s_deployment/**'
    branches: [ master ]
jobs:
  deploy:
     runs-on: self-hosted
     steps:
     - uses: actions/checkout@v2
     
     - name: Stopping docker adhanplayer docker container
       run: |
         sudo docker images
         sudo docker stop adhanplayer || true
         sudo docker rm -f adhanplayer || true
     - name: pulling docker image from docker hub
       run: |
         sudo docker pull phillogic/adhanplayer:latest
         sudo docker images     
         
     - name: Starting up docker adhanplayer docker container
       run: |
         sudo docker run -d --name adhanplayer -p 8000:8000 --device /dev/snd phillogic/adhanplayer:latest
         
     - name: Docker system prune
       run: sudo docker system prune -a -f
