name: k8s_deploy.yml

on:
  workflow_run:
    workflows: ["docker_build.yml"]
    types: 
      - completed
  workflow_dispatch:
  push:
    paths: 
      - 'k8s_deployment/**'
      - '**/workflows/k8s_deploy.yml'
    branches: [ master ]
jobs:
  k8s_deploy:
     runs-on: [ self-hosted ]
     steps:
     - uses: actions/checkout@v2
     
     - name: setup kubectl 
       run: |
        pwd
        ls -lh
        touch kubeconfig
        echo "${{ secrets.KUBECONFIG }}" > kubeconfig

     - name: kubectl apply 
       run: |
        ls -lh
        export KUBECONFIG="kubeconfig"
        kubectl delete namespace adhanplayer || true
        kubectl apply -f k8s_deployment/deployment.yaml

     - name: clean up old docker images
       run: | 
        sudo docker images
        sudo docker system prune --filter until=10m -f
        sudo docker images
