name: k8s_deploy.yml

on:
  workflow_dispatch:
  push:
    paths: 
      - 'k8s_deployment/**'
      - '**/workflows/k8s_deploy.yml'
    branches: [ master ]
jobs:
  deploy:
     runs-on: self-hosted
     steps:
     - uses: actions/checkout@v2
     
     - name: kubectl commands 
       run: |
        pwd
        ls -lh
        touch kubeconfig
        echo "${{ secrets.KUBECONFIG }}" > kubeconfig
        export KUBECONFIG="kubeconfig" 
        ls -lh
