name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v1.2.0
    - name: Docker Setup Buildx
  # You may pin to the exact commit or the version.
  # uses: docker/setup-buildx-action@0d135e0c2fc0dba0729c1a47ecfcf5a3c7f8579e
      uses: docker/setup-buildx-action@v1.3.0
      with:
        install: true
    -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
        
    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      uses: docker/build-push-action@v2.5.0
      with:
        # List of extra privileged entitlement (eg. network.host,security.insecure)
        tags: latest
        # List of build-time variables
        platforms: linux/arm/v7,linux/arm64
 

